name: CI/CD

on:
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-native:
    env:
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}

    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24.1.2'
          #distribution: 'graalvm'
          distribution: 'liberica'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      # Wird nur kompiliert. Es wird nichts getestet.
      - name: Build native image
        run: |
          ./gradlew clean nativeCompile 
          ls -la build/native/nativeCompile/

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: reports
          path: build/reports/tests/

      - name: Set up QEMU for amd64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Build Docker Image 
        run: |
          ./gradlew buildNativeDockerImage
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}


  build-jvm:
    env:
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}

    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '21'
          cache: 'gradle'

      - name: Build jar
        run: |
          ./gradlew clean build -i
          ls -la build/libs/

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: reports
          path: build/reports/tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install-qemu: true 

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Build Docker Image 
        run: |
          ./gradlew buildJavaDockerImage
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
